### ISSUE TITLE
pip安装后手动添加插件名到bot.py却显示找不到插件

### ISSUE THREAD

**Issue by LeonX86** [zxz0415/leetcode#1]
02-17 19:40:02 [ERROR] nonebot | Failed to import "nonebot-plugin-leetcode"
Traceback (most recent call last):
  File "bot.py", line 29, in <module>
    nonebot.load_plugin('nonebot-plugin-leetcode')
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 104, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/python3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot-plugin-leetcode'

**Comment by LeonX86** [comment]
> ...~（~
测试下来不是nonebot.load_plugin('nonebot_plugin_leetcode')
也不是nonebot-plugin-leetcode
不知道模块名是啥
或许是新的版本需要适配？

**Comment by Nranphy** [comment]
>**（b1官方文档）**
>load_plugin[#](https://v2.nonebot.dev/docs/tutorial/plugin/load-plugin#load_plugin)
>通过点分割模块名称来加载插件，通常用于加载单个插件或者是第三方插件。例如：
>nonebot.load_plugin("path.to.your.plugin")

说起来我好像理解错了×
我记得toml里自带写有导入plugins目录下的插件的，如果路径放对了应该是会自动导入的，~~我之前也这样写过，报错插件重复了~~；此外，放在plugins目录下的插件的名字应该就是目录的名字，如果是像我直接clone下来的话，插件名应该就只是leetcode吧
这个插件对b1是没做兼容的...~~（我之前用的时候是没改好这插件×现在正学着试图再写一个类似的，还没完工~~
我刚接触nb，上面说的东西不一定对，不过应该能提供一些参考吧×

**Comment by zxz0415** [comment]
> 02-17 19:40:02 [ERROR] nonebot | Failed to import "nonebot-plugin-leetcode" Traceback (most recent call last): File "bot.py", line 29, in nonebot.load_plugin('nonebot-plugin-leetcode') File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 28, in load_plugin return manager.load_plugin(module_path)
> 
> > File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 104, in load_plugin
> > module = importlib.import_module(name)
> > File "/usr/local/python3/lib/python3.8/importlib/**init**.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1014, in _gcd_import
> > File "", line 991, in _find_and_load
> > File "", line 973, in _find_and_load_unlocked
> > ModuleNotFoundError: No module named 'nonebot-plugin-leetcode'

我试了一下，导入方式你可以这样写`nonebot.load_plugin("leetcode")`

**Comment by LeonX86** [comment]
试过啦，name是这个但报错了，应该是不兼容

warnings.warn(
02-18 11:56:59 [ERROR] nonebot | Failed to import "leetcode"
Traceback (most recent call last):
File "bot.py", line 37, in
nonebot.load_plugin('leetcode')#力扣每日提醒
File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 30, in load_plugin
return manager.load_plugin(module_path)
File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 92, in load_plugin
module = importlib.import_module(name)
File "/usr/local/python3/lib/python3.8/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1014, in _gcd_import
File "", line 991, in _find_and_load
File "", line 975, in _find_and_load_unlocked
File "", line 671, in _load_unlocked
File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 181, in exec_module
super().exec_module(module)
File "", line 783, in exec_module
File "", line 219, in _call_with_frames_removed
File "/usr/local/python3/lib/python3.8/site-packages/leetcode/init.py", line 6, in
from .config import Config
File "/usr/local/python3/lib/python3.8/site-packages/leetcode/config.py", line 14, in
class Config(BaseSettings):
File "/usr/local/python3/lib/python3.8/site-packages/leetcode/config.py", line 18, in Config
leetcode_qq_friends: list[int]
TypeError: 'type' object is not subscriptable
02-18 11:56:59 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_status"
02-18 11:56:59 [WARNING] main | Always use nb run to start the bot instead of manually running!
02-18 11:56:59 [SUCCESS] nonebot | Running NoneBot...
02-18 11:56:59 [DEBUG] nonebot | Loaded adapters: OneBot V11
02-18 11:56:59 [INFO] uvicorn | Started server process [7873]
02-18 11:56:59 [INFO] uvicorn | Waiting for application startup.
02-18 11:57:00 [INFO] nonebot_plugin_htmlrender | Browser Started.


***@***.***
 
发件人： zxz0415
发送时间： 2022-02-18 13:46
收件人： zxz0415/leetcode
抄送： Leon; Author
主题： Re: [zxz0415/leetcode] pip安装后手动添加插件名到bot.py却显示找不到插件 (Issue #1)
02-17 19:40:02 [ERROR] nonebot | Failed to import "nonebot-plugin-leetcode" Traceback (most recent call last): File "bot.py", line 29, in nonebot.load_plugin('nonebot-plugin-leetcode') File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/load.py", line 28, in load_plugin return manager.load_plugin(module_path)
File "/usr/local/python3/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 104, in load_plugin
module = importlib.import_module(name)
File "/usr/local/python3/lib/python3.8/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1014, in _gcd_import
File "", line 991, in _find_and_load
File "", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot-plugin-leetcode'
我试了一下，导入方式你可以这样写nonebot.load_plugin("leetcode")
―
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
